- name: Configurar servidor web
  hosts: app
  become: true

  vars:
    titulo: "Laboratorio DevOps - Diego"
    mensagem: "Servidor configurado com Ansible e Jinja2."

  tasks:
    - name: Garantir que o Nginx esteja instalado
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: Garantir que o Nginx esteja iniciado e habilitado
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Publicar pagina do laboratorio
      ansible.builtin.template:
        src: ../templates/index.html.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
